// Generated by Scripts/build-web-assets.mjs from the verified release packs.
export const catalog = {
  "releaseTag": "v0.3.0-alpha.1",
  "cats": [
    {
      "id": "elsa",
      "name": {
        "en": "Elsa",
        "ko": "엘사",
        "ja": "エルサ"
      },
      "breed": {
        "en": "White Domestic Cat",
        "ko": "하얀 집고양이",
        "ja": "白いイエネコ"
      },
      "bundled": true
    },
    {
      "id": "K01",
      "name": {
        "en": "Hodu",
        "ko": "호두",
        "ja": "ホドゥ"
      },
      "breed": {
        "en": "Korean Shorthair · Brown Tabby",
        "ko": "코리안 숏헤어 · 고등어",
        "ja": "コリアンショートヘア · キジトラ"
      },
      "bundled": true
    },
    {
      "id": "K02",
      "name": {
        "en": "Cheese",
        "ko": "치즈",
        "ja": "チーズ"
      },
      "breed": {
        "en": "Korean Shorthair · Orange Tabby",
        "ko": "코리안 숏헤어 · 치즈",
        "ja": "コリアンショートヘア · 茶トラ"
      },
      "bundled": true
    },
    {
      "id": "K03",
      "name": {
        "en": "Mochi",
        "ko": "모찌",
        "ja": "モチ"
      },
      "breed": {
        "en": "Korean Shorthair · Calico",
        "ko": "코리안 숏헤어 · 삼색",
        "ja": "コリアンショートヘア · 三毛"
      },
      "bundled": true
    },
    {
      "id": "K04",
      "name": {
        "en": "Kongi",
        "ko": "콩이",
        "ja": "コンイ"
      },
      "breed": {
        "en": "Korean Shorthair · Tuxedo",
        "ko": "코리안 숏헤어 · 턱시도",
        "ja": "コリアンショートヘア · タキシード"
      },
      "bundled": false,
      "bytes": 11143665,
      "sha256": "134ce9943c6dc695b47952c8d616cded315b41fe4590393433e9d1198b6015b6",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-K04-v1.zip"
    },
    {
      "id": "K05",
      "name": {
        "en": "Dubu",
        "ko": "두부",
        "ja": "ドゥブ"
      },
      "breed": {
        "en": "Korean Shorthair · Black and White",
        "ko": "코리안 숏헤어 · 젖소",
        "ja": "コリアンショートヘア · 白黒"
      },
      "bundled": false,
      "bytes": 9840628,
      "sha256": "af68176298574db9f8a0c8a7a197802b157d116c7b94827362b79713272f9ed9",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-K05-v1.zip"
    },
    {
      "id": "K06",
      "name": {
        "en": "Gureum",
        "ko": "구름",
        "ja": "クルム"
      },
      "breed": {
        "en": "Russian Blue",
        "ko": "러시안 블루",
        "ja": "ロシアンブルー"
      },
      "bundled": false,
      "bytes": 18815018,
      "sha256": "58e2b52feef6d6f306f7d40966c49b4b03e103951d211b25f38c6cc8ac63ea2a",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-K06-v1.zip"
    },
    {
      "id": "K07",
      "name": {
        "en": "Seolgi",
        "ko": "설기",
        "ja": "ソルギ"
      },
      "breed": {
        "en": "Persian",
        "ko": "페르시안",
        "ja": "ペルシャ"
      },
      "bundled": false,
      "bytes": 11411634,
      "sha256": "2509a907c5cad414b3b938399822c51889da3fab29fcdfb077bfd55cf810f29a",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-K07-v1.zip"
    },
    {
      "id": "K08",
      "name": {
        "en": "Mandu",
        "ko": "만두",
        "ja": "マンドゥ"
      },
      "breed": {
        "en": "Scottish Fold",
        "ko": "스코티시 폴드",
        "ja": "スコティッシュフォールド"
      },
      "bundled": false,
      "bytes": 18959931,
      "sha256": "4e7d6264e5b40c4aeade24fc89e663ffab50285c3c06da84ca8f9cf58d33a11e",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-K08-v1.zip"
    },
    {
      "id": "K09",
      "name": {
        "en": "Bori",
        "ko": "보리",
        "ja": "ボリ"
      },
      "breed": {
        "en": "Siamese",
        "ko": "샴",
        "ja": "シャム"
      },
      "bundled": false,
      "bytes": 14305344,
      "sha256": "9b36079999c0e3974e735d50b04607f79e4a7ef2f04ad311a019c065ef3a5b27",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-K09-v1.zip"
    },
    {
      "id": "K10",
      "name": {
        "en": "Somi",
        "ko": "솜이",
        "ja": "ソミ"
      },
      "breed": {
        "en": "Turkish Angora",
        "ko": "터키시 앙고라",
        "ja": "ターキッシュアンゴラ"
      },
      "bundled": false,
      "bytes": 9732502,
      "sha256": "63fcacabd9d0072dac181b8bd311c6ba76ababab93002a5de22d3abd5b2f68db",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-K10-v1.zip"
    },
    {
      "id": "U01",
      "name": {
        "en": "Oliver",
        "ko": "올리버",
        "ja": "オリバー"
      },
      "breed": {
        "en": "American Shorthair",
        "ko": "아메리칸 숏헤어",
        "ja": "アメリカンショートヘア"
      },
      "bundled": false,
      "bytes": 22415574,
      "sha256": "bd7256328cdb08183f92e039c06089d36cafe1b4c545227abe58b74ffa31cec7",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-U01-v1.zip"
    },
    {
      "id": "U02",
      "name": {
        "en": "Milo",
        "ko": "마일로",
        "ja": "マイロ"
      },
      "breed": {
        "en": "Domestic Shorthair",
        "ko": "도메스틱 숏헤어",
        "ja": "ドメスティックショートヘア"
      },
      "bundled": false,
      "bytes": 14964673,
      "sha256": "f2b84663d70a099ed205efd72fa51acf19525a06b2fb3e709494e0bd4578325d",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-U02-v1.zip"
    },
    {
      "id": "U03",
      "name": {
        "en": "Maple",
        "ko": "메이플",
        "ja": "メープル"
      },
      "breed": {
        "en": "Domestic Longhair",
        "ko": "도메스틱 롱헤어",
        "ja": "ドメスティックロングヘア"
      },
      "bundled": false,
      "bytes": 20476258,
      "sha256": "0aeefd460e5989a15267ab77df8ac5315e1e301e19b34851ab7dc9f8708cc2c1",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-U03-v1.zip"
    },
    {
      "id": "U04",
      "name": {
        "en": "Coco",
        "ko": "코코",
        "ja": "ココ"
      },
      "breed": {
        "en": "Siamese",
        "ko": "샴",
        "ja": "シャム"
      },
      "bundled": false,
      "bytes": 9236160,
      "sha256": "65098bb29bdb5032049a6db736fadeba2adcbbf3a6938f8954e5fd888fced26b",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-U04-v1.zip"
    },
    {
      "id": "U05",
      "name": {
        "en": "Leo",
        "ko": "레오",
        "ja": "レオ"
      },
      "breed": {
        "en": "Maine Coon",
        "ko": "메인쿤",
        "ja": "メインクーン"
      },
      "bundled": false,
      "bytes": 22023222,
      "sha256": "a7e890056c48d3e83bc26769c8164da9be37713fb7aa8cfbeae00392d929ce44",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-U05-v1.zip"
    },
    {
      "id": "U06",
      "name": {
        "en": "Bella",
        "ko": "벨라",
        "ja": "ベラ"
      },
      "breed": {
        "en": "Ragdoll",
        "ko": "랙돌",
        "ja": "ラグドール"
      },
      "bundled": false,
      "bytes": 15917481,
      "sha256": "8ae92351ab1979dbe30b737db1c8191935153ce2a9877bca350b986b4a021671",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-U06-v1.zip"
    },
    {
      "id": "U07",
      "name": {
        "en": "Smokey",
        "ko": "스모키",
        "ja": "スモーキー"
      },
      "breed": {
        "en": "Russian Blue",
        "ko": "러시안 블루",
        "ja": "ロシアンブルー"
      },
      "bundled": false,
      "bytes": 18278706,
      "sha256": "dd1cd0f2aa00c1167906b9d3fa10a96a0146338ead3b94a253d5b80352d3f3aa",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-U07-v1.zip"
    },
    {
      "id": "U08",
      "name": {
        "en": "Onyx",
        "ko": "오닉스",
        "ja": "オニキス"
      },
      "breed": {
        "en": "Bombay",
        "ko": "봄베이",
        "ja": "ボンベイ"
      },
      "bundled": false,
      "bytes": 12610310,
      "sha256": "8e28311953f8393f61dd6d84d34aac46da9c7fb050a2c3f3a1b253427d3ec4da",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-U08-v1.zip"
    },
    {
      "id": "U09",
      "name": {
        "en": "Sunny",
        "ko": "써니",
        "ja": "サニー"
      },
      "breed": {
        "en": "Bengal",
        "ko": "벵갈",
        "ja": "ベンガル"
      },
      "bundled": false,
      "bytes": 18397423,
      "sha256": "960432bdc660a4f1d8280418d263c1861a0598fd9369e4cbf2aac7f36dc7ae81",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-U09-v1.zip"
    },
    {
      "id": "U10",
      "name": {
        "en": "Daisy",
        "ko": "데이지",
        "ja": "デイジー"
      },
      "breed": {
        "en": "Persian",
        "ko": "페르시안",
        "ja": "ペルシャ"
      },
      "bundled": false,
      "bytes": 25087256,
      "sha256": "9fa5d54ceefd6d23051a463038f384c00c33169624874fd470f0f624f4bf8f83",
      "url": "https://github.com/kimdwkimdw/meownitor/releases/download/v0.3.0-alpha.1/Meownitor-Cat-U10-v1.zip"
    }
  ]
};
